export default {
    FETCH_IN_PROGRESS: "FETCH_IN_PROGRESS",
    RECEIVE_SUBMISSIONS: "RECEIVE_SUBMISSION",
    SUBMISSION_LOAD_ERROR: "SUBMISSION_LOAD_ERROR",
    RECEIVE_SUBMISSION_BY_NO: "RECEIVE_SUBMISSION_BY_NO",
    RECEIVE_SUBMISSION_BY_UNDERWRITER: "RECEIVE_SUBMISSION_BY_UNDERWRITER",
    FETCH_SUBMISSION_BY_NO_IN_PROGRESS: "FETCH_SUBMISSION_BY_NO_IN_PROGRESS",
    RECEIVE_REJECTED_SUBMISSIONS_BY: "RECEIVE_REJECTED_SUBMISSIONS_BY"
};
